# Generated by Django 5.2.14 on 2026-06-12 10:54

import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('tag', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BULDING INSPECTION AND PERMITS', 'Building Inspection and Permits'), ('ZONING', 'Zoning'), ('COMMERCIAL', 'Commercial')], max_length=48)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'faqcategory',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gallery_photos/')),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'gallery_M',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='Upload image with 1:1 aspect ratio(100px x 100px) ', null=True, upload_to='testimonials/')),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('star', models.IntegerField(default=5)),
                ('created_by', models.CharField(max_length=8)),
                ('updated_by', models.CharField(max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='UPIPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('THREE_MONTH', '3 Months'), ('SIX_MONTH', '6 Months'), ('ONE_YEAR', '1 Year')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utr_number', models.CharField(blank=True, help_text='UTR / Transaction reference number (optional)', max_length=50)),
                ('screenshot', models.ImageField(upload_to='upi_screenshots/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'UPI Payment Request',
                'verbose_name_plural': 'UPI Payment Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
