# Generated by Django 5.2.14 on 2026-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('class_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('module_name', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20)),
            ],
            options={
                'db_table': 'master_permission',
            },
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('CUS_IOS_APP', 'IOS App'), ('CUS_ANDROID_APP', 'Android App')], default='CUS_ANDROID_APP', max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('released_on', models.DateTimeField(auto_now_add=True)),
                ('datamode', models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=5)),
            ],
            options={
                'db_table': 'version_control',
            },
        ),
    ]
